-- Create countries table with all world countries
-- This migration creates a comprehensive countries table for nationality and visa status selections

CREATE TABLE IF NOT EXISTS countries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(3) NOT NULL UNIQUE COMMENT 'ISO 3166-1 alpha-3 code',
    is_active BOOLEAN DEFAULT TRUE COMMENT 'Whether this country is available for selection',
    sort_order INT DEFAULT 999 COMMENT 'Custom sort order, lower numbers appear first',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    INDEX idx_active (is_active),
    INDEX idx_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Insert all world countries with priority for common ones
INSERT INTO countries (name, code, sort_order) VALUES 
-- Priority countries (commonly used in UK context)
('United Kingdom', 'GBR', 1),
('British', 'BRI', 2), -- Keep for backward compatibility
('Ireland', 'IRL', 3),
('European Union', 'EUR', 4), -- Keep for backward compatibility  
('Commonwealth', 'CWL', 5), -- Keep for backward compatibility

-- Major European countries
('France', 'FRA', 10),
('Germany', 'DEU', 11),
('Spain', 'ESP', 12),
('Italy', 'ITA', 13),
('Poland', 'POL', 14),
('Netherlands', 'NLD', 15),
('Belgium', 'BEL', 16),
('Portugal', 'PRT', 17),
('Greece', 'GRC', 18),
('Czech Republic', 'CZE', 19),
('Hungary', 'HUN', 20),
('Austria', 'AUT', 21),
('Sweden', 'SWE', 22),
('Denmark', 'DNK', 23),
('Finland', 'FIN', 24),
('Norway', 'NOR', 25),
('Switzerland', 'CHE', 26),
('Romania', 'ROU', 27),
('Bulgaria', 'BGR', 28),
('Croatia', 'HRV', 29),
('Slovakia', 'SVK', 30),
('Slovenia', 'SVN', 31),
('Lithuania', 'LTU', 32),
('Latvia', 'LVA', 33),
('Estonia', 'EST', 34),
('Luxembourg', 'LUX', 35),
('Malta', 'MLT', 36),
('Cyprus', 'CYP', 37),

-- Major Commonwealth and international countries (high priority for UK context)
('India', 'IND', 40),
('Pakistan', 'PAK', 41),
('Bangladesh', 'BGD', 42),
('Nigeria', 'NGA', 43),
('Ghana', 'GHA', 44),
('Kenya', 'KEN', 45),
('Jamaica', 'JAM', 46),
('South Africa', 'ZAF', 47),

-- Major Western countries
('United States', 'USA', 50),
('Canada', 'CAN', 51),
('Australia', 'AUS', 52),
('New Zealand', 'NZL', 53),
-- Major Asian and Middle Eastern countries
('China', 'CHN', 55),
('Japan', 'JPN', 56),
('South Korea', 'KOR', 57),
('Philippines', 'PHL', 58),
('Thailand', 'THA', 59),
('Vietnam', 'VNM', 60),
('Malaysia', 'MYS', 61),
('Singapore', 'SGP', 62),
('Indonesia', 'IDN', 63),
('Sri Lanka', 'LKA', 64),
('Afghanistan', 'AFG', 65),
('Iran', 'IRN', 66),
('Iraq', 'IRQ', 67),
('Turkey', 'TUR', 68),
('Syria', 'SYR', 69),

-- Major American countries
('Brazil', 'BRA', 70),
('Mexico', 'MEX', 71),
('Argentina', 'ARG', 72),
('Chile', 'CHL', 73),
('Colombia', 'COL', 74),
('Peru', 'PER', 75),
('Venezuela', 'VEN', 76),

-- European non-EU and other major countries
('Russia', 'RUS', 80),
('Ukraine', 'UKR', 81),
('Belarus', 'BLR', 82),
('Israel', 'ISR', 83),
('Saudi Arabia', 'SAU', 84),
('United Arab Emirates', 'ARE', 85),
('Egypt', 'EGY', 86),
('Morocco', 'MAR', 87),
('Algeria', 'DZA', 88),
('Tunisia', 'TUN', 89),
('Libya', 'LBY', 90),
('Ethiopia', 'ETH', 91),
('Somalia', 'SOM', 92),
('Sudan', 'SDN', 93),
('Zimbabwe', 'ZWE', 94),
('Botswana', 'BWA', 95),
('Zambia', 'ZMB', 96),

-- Rest of the world (alphabetical)
('Albania', 'ALB', 100),
('Andorra', 'AND', 100),
('Angola', 'AGO', 100),
('Antigua and Barbuda', 'ATG', 100),
('Armenia', 'ARM', 100),
('Azerbaijan', 'AZE', 100),
('Bahamas', 'BHS', 100),
('Bahrain', 'BHR', 100),
('Barbados', 'BRB', 100),
('Belize', 'BLZ', 100),
('Benin', 'BEN', 100),
('Bhutan', 'BTN', 100),
('Bolivia', 'BOL', 100),
('Bosnia and Herzegovina', 'BIH', 100),
('Brunei', 'BRN', 100),
('Burkina Faso', 'BFA', 100),
('Burundi', 'BDI', 100),
('Cambodia', 'KHM', 100),
('Cameroon', 'CMR', 100),
('Cape Verde', 'CPV', 100),
('Central African Republic', 'CAF', 100),
('Chad', 'TCD', 100),
('Comoros', 'COM', 100),
('Congo', 'COG', 100),
('Costa Rica', 'CRI', 100),
('Côte d''Ivoire', 'CIV', 100),
('Cuba', 'CUB', 100),
('Djibouti', 'DJI', 100),
('Dominica', 'DMA', 100),
('Dominican Republic', 'DOM', 100),
('East Timor', 'TLS', 100),
('Ecuador', 'ECU', 100),
('El Salvador', 'SLV', 100),
('Equatorial Guinea', 'GNQ', 100),
('Eritrea', 'ERI', 100),
('Eswatini', 'SWZ', 100),
('Fiji', 'FJI', 100),
('Gabon', 'GAB', 100),
('Gambia', 'GMB', 100),
('Georgia', 'GEO', 100),
('Grenada', 'GRD', 100),
('Guatemala', 'GTM', 100),
('Guinea', 'GIN', 100),
('Guinea-Bissau', 'GNB', 100),
('Guyana', 'GUY', 100),
('Haiti', 'HTI', 100),
('Honduras', 'HND', 100),
('Iceland', 'ISL', 100),
('Jordan', 'JOR', 100),
('Kazakhstan', 'KAZ', 100),
('Kiribati', 'KIR', 100),
('Kuwait', 'KWT', 100),
('Kyrgyzstan', 'KGZ', 100),
('Laos', 'LAO', 100),
('Lebanon', 'LBN', 100),
('Lesotho', 'LSO', 100),
('Liberia', 'LBR', 100),
('Liechtenstein', 'LIE', 100),
('Madagascar', 'MDG', 100),
('Malawi', 'MWI', 100),
('Maldives', 'MDV', 100),
('Mali', 'MLI', 100),
('Marshall Islands', 'MHL', 100),
('Mauritania', 'MRT', 100),
('Mauritius', 'MUS', 100),
('Micronesia', 'FSM', 100),
('Moldova', 'MDA', 100),
('Monaco', 'MCO', 100),
('Mongolia', 'MNG', 100),
('Montenegro', 'MNE', 100),
('Mozambique', 'MOZ', 100),
('Myanmar', 'MMR', 100),
('Namibia', 'NAM', 100),
('Nauru', 'NRU', 100),
('Nepal', 'NPL', 100),
('Nicaragua', 'NIC', 100),
('Niger', 'NER', 100),
('North Korea', 'PRK', 100),
('North Macedonia', 'MKD', 100),
('Oman', 'OMN', 100),
('Palau', 'PLW', 100),
('Panama', 'PAN', 100),
('Papua New Guinea', 'PNG', 100),
('Paraguay', 'PRY', 100),
('Qatar', 'QAT', 100),
('Rwanda', 'RWA', 100),
('Saint Kitts and Nevis', 'KNA', 100),
('Saint Lucia', 'LCA', 100),
('Saint Vincent and the Grenadines', 'VCT', 100),
('Samoa', 'WSM', 100),
('San Marino', 'SMR', 100),
('São Tomé and Príncipe', 'STP', 100),
('Senegal', 'SEN', 100),
('Serbia', 'SRB', 100),
('Seychelles', 'SYC', 100),
('Sierra Leone', 'SLE', 100),
('Solomon Islands', 'SLB', 100),
('South Sudan', 'SSD', 100),
('Suriname', 'SUR', 100),
('Tajikistan', 'TJK', 100),
('Tanzania', 'TZA', 100),
('Togo', 'TGO', 100),
('Tonga', 'TON', 100),
('Trinidad and Tobago', 'TTO', 100),
('Turkmenistan', 'TKM', 100),
('Tuvalu', 'TUV', 100),
('Uganda', 'UGA', 100),
('Uruguay', 'URY', 100),
('Uzbekistan', 'UZB', 100),
('Vanuatu', 'VUT', 100),
('Vatican City', 'VAT', 100),
('Yemen', 'YEM', 100);

-- Create a special "Other" option for edge cases
INSERT INTO countries (name, code, sort_order) VALUES (' er', 'OTH', 998);
